import type { CountryMobilityPack } from './CountryMobilityMap';

export const COUNTRY_MOBILITY_EXTENDED: Record<string, CountryMobilityPack> = {
  'Alemania': {
    country: 'Alemania',
    visaTracks: [
      {
        id: 'de-student',
        type: 'student',
        title: 'Studentenvisum / Aufenthalt zu Studienzwecken',
        summary: 'Ruta academica con permiso laboral parcial segun normativa vigente.',
        officialUrl: 'https://www.make-it-in-germany.com/',
        eligibility: ['Admisión universitaria', 'Fondos bloqueados', 'Seguro medico'],
        typicalRoles: ['Werkstudent', 'Soporte IT junior', 'Hospitality support'],
        requiredSkills: ['Alemán', 'Inglés', 'Atención al cliente'],
        caution: 'Verifica limites de horas de trabajo y condiciones de residencia.',
      },
      {
        id: 'de-skilled',
        type: 'skilled',
        title: 'Skilled Worker / EU Blue Card',
        summary: 'Ruta para perfiles cualificados con contrato y salario minimo aplicable.',
        officialUrl: 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card',
        eligibility: ['Titulo reconocido o experiencia equivalente', 'Oferta laboral'],
        typicalRoles: ['Software engineer', 'Nurse', 'Electrician', 'Logistics specialist'],
        requiredSkills: ['TypeScript', 'Python', 'Enfermería', 'Electricidad básica'],
        caution: 'Revisar reconocimiento de titulo y salario umbral actualizado.',
      },
    ],
    portals: [
      { id: 'de-stepstone', name: 'StepStone DE', url: 'https://www.stepstone.de/', category: 'general', sectors: ['all'] },
      { id: 'de-arbeitsagentur', name: 'BA Jobbörse', url: 'https://www.arbeitsagentur.de/jobsuche/', category: 'government', sectors: ['all'] },
      { id: 'de-linkedin', name: 'LinkedIn Jobs DE', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'de-makeit', name: 'Make it in Germany Jobs', url: 'https://www.make-it-in-germany.com/en/working-in-germany/job-listings', category: 'government', sectors: ['all'] },
      { id: 'de-hotelcareer', name: 'Hotelcareer', url: 'https://www.hotelcareer.de/', category: 'niche', sectors: ['hospitality'] },
    ],
  },
  'Austria': {
    country: 'Austria',
    visaTracks: [
      {
        id: 'at-student',
        type: 'student',
        title: 'Residence Permit - Student',
        summary: 'Ruta de estudios con empleo parcial segun categoria de permiso.',
        officialUrl: 'https://www.oesterreich.gv.at/en/themen/leben_in_oesterreich/aufenthalt.html',
        eligibility: ['Admisión academica', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Hospitality support', 'Retail assistant', 'Junior office roles'],
        requiredSkills: ['Alemán', 'Inglés', 'Atención al cliente'],
        caution: 'Consultar condiciones de empleo para estudiantes en cada estado federal.',
      },
      {
        id: 'at-rwr',
        type: 'skilled',
        title: 'Red-White-Red Card',
        summary: 'Ruta para personal cualificado en sectores con demanda.',
        officialUrl: 'https://www.migration.gv.at/en/',
        eligibility: ['Oferta laboral', 'Puntaje por cualificacion/idioma/experiencia'],
        typicalRoles: ['Engineer', 'Developer', 'Healthcare assistant'],
        requiredSkills: ['Inglés', 'Alemán', 'SQL', 'Enfermería'],
        caution: 'El sistema de puntos y ocupaciones se actualiza periodicamente.',
      },
    ],
    portals: [
      { id: 'at-karriere', name: 'karriere.at', url: 'https://www.karriere.at/', category: 'general', sectors: ['all'] },
      { id: 'at-ams', name: 'AMS eJob-Room', url: 'https://jobs.ams.at/public/emps/', category: 'government', sectors: ['all'] },
      { id: 'at-linkedin', name: 'LinkedIn Jobs AT', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'at-gastrojobs', name: 'GastroJobs Austria', url: 'https://www.gastrojobs.at/', category: 'niche', sectors: ['hospitality'] },
    ],
  },
  'Bélgica': {
    country: 'Bélgica',
    visaTracks: [
      {
        id: 'be-student',
        type: 'student',
        title: 'Long Stay Visa D (student)',
        summary: 'Ruta de estudio para programas superiores y empleo parcial regulado.',
        officialUrl: 'https://dofi.ibz.be/en/themes/third-country-nationals/study',
        eligibility: ['Carta de admision', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Hospitality support', 'Logistics support', 'Retail'],
        requiredSkills: ['Francés', 'Neerlandés', 'Inglés'],
        caution: 'Revisar reglas por region (Flandes, Valonia, Bruselas).',
      },
      {
        id: 'be-skilled',
        type: 'sponsored',
        title: 'Single Permit (work and residence)',
        summary: 'Ruta laboral con permiso unico de residencia y trabajo.',
        officialUrl: 'https://economy-employment.brussels/single-permit',
        eligibility: ['Oferta laboral valida', 'Cumplimiento salarial y documental'],
        typicalRoles: ['Developer', 'Accounting specialist', 'Logistics coordinator'],
        requiredSkills: ['SQL', 'Python', 'Logística de almacén'],
        caution: 'Los requisitos practicos dependen de la region y ocupacion.',
      },
    ],
    portals: [
      { id: 'be-vdab', name: 'VDAB Jobs', url: 'https://www.vdab.be/', category: 'government', sectors: ['all'] },
      { id: 'be-forem', name: 'Le Forem', url: 'https://www.leforem.be/', category: 'government', sectors: ['all'] },
      { id: 'be-stepstone', name: 'StepStone BE', url: 'https://www.stepstone.be/', category: 'general', sectors: ['all'] },
      { id: 'be-linkedin', name: 'LinkedIn Jobs BE', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Dinamarca': {
    country: 'Dinamarca',
    visaTracks: [
      {
        id: 'dk-student',
        type: 'student',
        title: 'Residence Permit for Study',
        summary: 'Ruta de estudios con trabajo parcial permitido segun condiciones.',
        officialUrl: 'https://www.nyidanmark.dk/',
        eligibility: ['Admisión educativa', 'Fondos', 'Seguro y documentacion'],
        typicalRoles: ['Hospitality', 'Retail', 'Student assistant'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Verificar limites de horas y temporadas de trabajo permitidas.',
      },
      {
        id: 'dk-positive-list',
        type: 'skilled',
        title: 'Positive List / Pay Limit Scheme',
        summary: 'Ruta para ocupaciones en demanda o con umbral salarial.',
        officialUrl: 'https://www.nyidanmark.dk/en-GB/Applying/Work',
        eligibility: ['Oferta laboral', 'Cumplimiento de lista o salario minimo'],
        typicalRoles: ['Software developer', 'Engineer', 'Healthcare professional'],
        requiredSkills: ['Python', 'React', 'Enfermería'],
        caution: 'Las listas y thresholds cambian periodicamente.',
      },
    ],
    portals: [
      { id: 'dk-jobnet', name: 'Jobnet', url: 'https://www.jobnet.dk/', category: 'government', sectors: ['all'] },
      { id: 'dk-workindenmark', name: 'Work in Denmark', url: 'https://www.workindenmark.dk/', category: 'government', sectors: ['all'] },
      { id: 'dk-jobindex', name: 'Jobindex', url: 'https://www.jobindex.dk/', category: 'general', sectors: ['all'] },
      { id: 'dk-linkedin', name: 'LinkedIn Jobs DK', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Francia': {
    country: 'Francia',
    visaTracks: [
      {
        id: 'fr-student',
        type: 'student',
        title: 'Visa long sejour etudiant',
        summary: 'Ruta de estudios con empleo parcial bajo condiciones regladas.',
        officialUrl: 'https://france-visas.gouv.fr/',
        eligibility: ['Admisión academica', 'Fondos y seguro', 'Documentacion consular'],
        typicalRoles: ['Hospitality support', 'Retail assistant', 'Campus roles'],
        requiredSkills: ['Francés', 'Inglés', 'Atención al cliente'],
        caution: 'Consultar reglas vigentes de horas laborales para estudiantes.',
      },
      {
        id: 'fr-talent',
        type: 'skilled',
        title: 'Passeport Talent / Work Permit',
        summary: 'Ruta para perfiles cualificados, tech y cientificos con contrato.',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/N110',
        eligibility: ['Oferta laboral', 'Perfil cualificado y requisitos de categoria'],
        typicalRoles: ['Software engineer', 'Data analyst', 'Healthcare staff'],
        requiredSkills: ['React', 'Python', 'SQL', 'Enfermería'],
        caution: 'Verificar categoria aplicable y requisitos de cada prefectura.',
      },
    ],
    portals: [
      { id: 'fr-francetravail', name: 'France Travail', url: 'https://candidat.francetravail.fr/offres/recherche', category: 'government', sectors: ['all'] },
      { id: 'fr-apec', name: 'APEC', url: 'https://www.apec.fr/', category: 'general', sectors: ['all'] },
      { id: 'fr-indeed', name: 'Indeed France', url: 'https://fr.indeed.com/', category: 'general', sectors: ['all'] },
      { id: 'fr-linkedin', name: 'LinkedIn Jobs FR', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'fr-wttj', name: 'Welcome to the Jungle', url: 'https://www.welcometothejungle.com/fr', category: 'niche', sectors: ['tech', 'startup'] },
    ],
  },
  'Países Bajos': {
    country: 'Países Bajos',
    visaTracks: [
      {
        id: 'nl-student',
        type: 'student',
        title: 'Student Residence Permit',
        summary: 'Ruta educativa con empleo parcial bajo condiciones migratorias.',
        officialUrl: 'https://ind.nl/en',
        eligibility: ['Admisión educativa', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Hospitality', 'Warehouse support', 'Retail assistant'],
        requiredSkills: ['Inglés', 'Neerlandés', 'Atención al cliente'],
        caution: 'Consultar limites de empleo estudiantil y permisos complementarios.',
      },
      {
        id: 'nl-high-skilled',
        type: 'sponsored',
        title: 'Highly Skilled Migrant',
        summary: 'Ruta patrocinada para perfiles altamente cualificados.',
        officialUrl: 'https://ind.nl/en/residence-permits/work/highly-skilled-migrant',
        eligibility: ['Oferta de sponsor reconocido', 'Cumplir salario minimo de categoria'],
        typicalRoles: ['Software engineer', 'Data engineer', 'Logistics analyst'],
        requiredSkills: ['TypeScript', 'Python', 'SQL', 'Logística de almacén'],
        caution: 'Revisar lista de sponsors reconocidos y umbrales salariales.',
      },
    ],
    portals: [
      { id: 'nl-werk', name: 'Werk.nl', url: 'https://www.werk.nl/', category: 'government', sectors: ['all'] },
      { id: 'nl-indeed', name: 'Indeed NL', url: 'https://nl.indeed.com/', category: 'general', sectors: ['all'] },
      { id: 'nl-linkedin', name: 'LinkedIn Jobs NL', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'nl-iamsterdam', name: 'I amsterdam Jobs', url: 'https://www.iamsterdam.com/en/work', category: 'government', sectors: ['all'] },
      { id: 'nl-undutchables', name: 'Undutchables', url: 'https://undutchables.nl/jobs', category: 'niche', sectors: ['multilingual', 'tech'] },
    ],
  },
  'Reino Unido': {
    country: 'Reino Unido',
    visaTracks: [
      {
        id: 'uk-student',
        type: 'student',
        title: 'Student Visa (UK)',
        summary: 'Ruta de estudios con empleo parcial sujeto a reglas del visado.',
        officialUrl: 'https://www.gov.uk/student-visa',
        eligibility: ['CAS de institucion', 'Fondos', 'Inglés requerido'],
        typicalRoles: ['Retail', 'Hospitality', 'Campus support'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Revisar horas maximas de empleo permitidas por term-time.',
      },
      {
        id: 'uk-skilled-worker',
        type: 'sponsored',
        title: 'Skilled Worker Visa',
        summary: 'Ruta con sponsor licenciado para ocupaciones elegibles.',
        officialUrl: 'https://www.gov.uk/skilled-worker-visa',
        eligibility: ['Oferta laboral de sponsor', 'Nivel salarial y ocupacional'],
        typicalRoles: ['Software engineer', 'Care worker', 'Chef', 'Nurse'],
        requiredSkills: ['TypeScript', 'Cuidado de personas mayores', 'Cocina profesional', 'Enfermería'],
        caution: 'Requisitos de salario y lista ocupacional cambian por policy updates.',
      },
      {
        id: 'uk-yms',
        type: 'work_and_travel',
        title: 'Youth Mobility Scheme (eligible nationals)',
        summary: 'Ruta temporal tipo work-and-travel para nacionalidades elegibles.',
        officialUrl: 'https://www.gov.uk/youth-mobility',
        eligibility: ['Nacionalidad elegible', 'Edad y fondos minimos'],
        typicalRoles: ['Hospitality', 'Warehouse', 'Customer support'],
        requiredSkills: ['Inglés', 'Atención al cliente', 'Manual Handling'],
        caution: 'No disponible para todas las nacionalidades; verificar elegibilidad.',
      },
    ],
    portals: [
      { id: 'uk-findajob', name: 'Find a Job (GOV.UK)', url: 'https://findajob.dwp.gov.uk/', category: 'government', sectors: ['all'] },
      { id: 'uk-indeed', name: 'Indeed UK', url: 'https://uk.indeed.com/', category: 'general', sectors: ['all'] },
      { id: 'uk-linkedin', name: 'LinkedIn Jobs UK', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'uk-cwjobs', name: 'CWJobs', url: 'https://www.cwjobs.co.uk/', category: 'niche', sectors: ['tech'] },
      { id: 'uk-carehome', name: 'Care Home Jobs', url: 'https://www.carehome.co.uk/jobs/', category: 'niche', sectors: ['caregiving', 'healthcare'] },
    ],
  },
  'Suiza': {
    country: 'Suiza',
    visaTracks: [
      {
        id: 'ch-student',
        type: 'student',
        title: 'Student Residence Permit',
        summary: 'Ruta academica con requisitos cantonales y limite de empleo parcial.',
        officialUrl: 'https://www.sem.admin.ch/sem/en/home.html',
        eligibility: ['Admisión educativa', 'Fondos suficientes', 'Seguro medico'],
        typicalRoles: ['Hospitality support', 'Administrative support'],
        requiredSkills: ['Alemán', 'Francés', 'Inglés'],
        caution: 'Los requisitos pueden variar por canton y nacionalidad.',
      },
      {
        id: 'ch-work-permit',
        type: 'sponsored',
        title: 'Work Permit (L/B permit)',
        summary: 'Ruta laboral con empleador y cupos para extracomunitarios.',
        officialUrl: 'https://www.ch.ch/en/foreign-nationals-in-switzerland/working-in-switzerland/',
        eligibility: ['Oferta laboral', 'Perfil cualificado', 'Aprobacion cantonal/federal'],
        typicalRoles: ['Engineer', 'Software developer', 'Healthcare professional'],
        requiredSkills: ['Python', 'Java', 'Enfermería', 'Inglés'],
        caution: 'Hay cupos anuales y criterios de prioridad para mercado local.',
      },
    ],
    portals: [
      { id: 'ch-jobroom', name: 'Job-Room.ch', url: 'https://www.job-room.ch/', category: 'government', sectors: ['all'] },
      { id: 'ch-jobs', name: 'jobs.ch', url: 'https://www.jobs.ch/', category: 'general', sectors: ['all'] },
      { id: 'ch-linkedin', name: 'LinkedIn Jobs CH', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'ch-hotelcareer', name: 'HotelCareer CH', url: 'https://www.hotelcareer.ch/', category: 'niche', sectors: ['hospitality'] },
    ],
  },
  'Estados Unidos': {
    country: 'Estados Unidos',
    visaTracks: [
      {
        id: 'us-student-f1',
        type: 'student',
        title: 'F-1 Student Pathway (on-campus/OPT)',
        summary: 'Ruta de estudio con opciones de empleo en campus y practicas autorizadas.',
        officialUrl: 'https://studyinthestates.dhs.gov/',
        eligibility: ['I-20 emitido por institucion', 'Fondos', 'Mantenimiento de estatus'],
        typicalRoles: ['On-campus roles', 'Internships', 'Entry support roles'],
        requiredSkills: ['Inglés', 'Atención al cliente', 'SQL'],
        caution: 'Cada modalidad de empleo exige autorizacion especifica.',
      },
      {
        id: 'us-sponsored',
        type: 'sponsored',
        title: 'Employer-Sponsored Work Visa (H-1B / others)',
        summary: 'Ruta laboral patrocinada por empleador para roles elegibles.',
        officialUrl: 'https://www.uscis.gov/working-in-the-united-states',
        eligibility: ['Oferta de empleador sponsor', 'Categoria de visa aplicable'],
        typicalRoles: ['Software engineer', 'Nurse', 'Data analyst', 'Chef'],
        requiredSkills: ['TypeScript', 'Python', 'Enfermería', 'Cocina profesional'],
        caution: 'No todas las categorias son accesibles desde el exterior sin sponsor previo.',
      },
      {
        id: 'us-j1',
        type: 'work_and_travel',
        title: 'J-1 Exchange Programs',
        summary: 'Programas de intercambio con modalidades de trabajo temporal.',
        officialUrl: 'https://j1visa.state.gov/',
        eligibility: ['Sponsor autorizado', 'Categoria J-1 especifica'],
        typicalRoles: ['Seasonal hospitality', 'Camp counselor', 'Cultural exchange roles'],
        requiredSkills: ['Inglés', 'Atención al cliente', 'Manual Handling'],
        caution: 'Cada categoria J-1 tiene reglas y duracion distintas.',
      },
    ],
    portals: [
      { id: 'us-indeed', name: 'Indeed US', url: 'https://www.indeed.com/', category: 'general', sectors: ['all'] },
      { id: 'us-linkedin', name: 'LinkedIn Jobs US', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'us-dol', name: 'USAJOBS / DOL resources', url: 'https://www.usajobs.gov/', category: 'government', sectors: ['all'] },
      { id: 'us-dice', name: 'Dice', url: 'https://www.dice.com/', category: 'niche', sectors: ['tech'] },
      { id: 'us-hcareers', name: 'Hcareers', url: 'https://www.hcareers.com/', category: 'niche', sectors: ['hospitality'] },
    ],
  },
  'México': {
    country: 'México',
    visaTracks: [
      {
        id: 'mx-student',
        type: 'student',
        title: 'Visa de estudiante',
        summary: 'Ruta academica con permisos de trabajo segun autorizacion expresa.',
        officialUrl: 'https://www.gob.mx/inm',
        eligibility: ['Carta de aceptación', 'Fondos', 'Documentacion consular'],
        typicalRoles: ['Soporte academico', 'Hospitality support', 'Retail'],
        requiredSkills: ['Español funcional', 'Atención al cliente'],
        caution: 'La autorizacion de empleo para estudiantes no es automatica.',
      },
      {
        id: 'mx-temp-work',
        type: 'sponsored',
        title: 'Residente temporal con permiso de trabajo',
        summary: 'Ruta con oferta de empleo y tramite ante INM.',
        officialUrl: 'https://www.gob.mx/tramites/ficha/solicitud-de-visa-por-oferta-de-empleo/SRE164',
        eligibility: ['Oferta laboral', 'Patrocinio del empleador y expediente migratorio'],
        typicalRoles: ['Manufactura', 'Logística', 'IT services'],
        requiredSkills: ['Logística de almacén', 'SQL', 'Atención al cliente'],
        caution: 'Los tiempos de tramite dependen de consulado y validacion interna.',
      },
    ],
    portals: [
      { id: 'mx-occ', name: 'OCC Mundial', url: 'https://www.occ.com.mx/', category: 'general', sectors: ['all'] },
      { id: 'mx-computrabajo', name: 'Computrabajo MX', url: 'https://mx.computrabajo.com/', category: 'general', sectors: ['all'] },
      { id: 'mx-empleo', name: 'Portal del Empleo', url: 'https://www.empleo.gob.mx/', category: 'government', sectors: ['all'] },
      { id: 'mx-linkedin', name: 'LinkedIn Jobs MX', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Chile': {
    country: 'Chile',
    visaTracks: [
      {
        id: 'cl-student',
        type: 'student',
        title: 'Residencia temporal para estudios',
        summary: 'Ruta de estudios con condiciones de trabajo segun autorizacion.',
        officialUrl: 'https://serviciomigraciones.cl/',
        eligibility: ['Aceptacion academica', 'Fondos', 'Documentacion migratoria'],
        typicalRoles: ['Soporte administrativo', 'Retail', 'Hospitality support'],
        requiredSkills: ['Español', 'Atención al cliente'],
        caution: 'Verifica permisos laborales para estudiantes antes de postular.',
      },
      {
        id: 'cl-work',
        type: 'sponsored',
        title: 'Residencia temporal por motivos laborales',
        summary: 'Ruta con contrato de trabajo y tramitacion ante migraciones.',
        officialUrl: 'https://tramites.serviciomigraciones.cl/',
        eligibility: ['Oferta laboral valida', 'Cumplimiento documental'],
        typicalRoles: ['Tech roles', 'Logistics', 'Construction support'],
        requiredSkills: ['SQL', 'React', 'Logística de almacén'],
        caution: 'Los requisitos documentales pueden variar por nacionalidad.',
      },
    ],
    portals: [
      { id: 'cl-laborum', name: 'Laborum', url: 'https://www.laborum.cl/', category: 'general', sectors: ['all'] },
      { id: 'cl-computrabajo', name: 'Computrabajo CL', url: 'https://cl.computrabajo.com/', category: 'general', sectors: ['all'] },
      { id: 'cl-bne', name: 'Bolsa Nacional de Empleo', url: 'https://www.bne.cl/', category: 'government', sectors: ['all'] },
      { id: 'cl-linkedin', name: 'LinkedIn Jobs CL', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Colombia': {
    country: 'Colombia',
    visaTracks: [
      {
        id: 'co-student',
        type: 'student',
        title: 'Visa tipo V - estudiante',
        summary: 'Ruta academica para programas formales con permisos segun normativa.',
        officialUrl: 'https://www.cancilleria.gov.co/',
        eligibility: ['Carta de admision', 'Fondos', 'Seguro y documentos'],
        typicalRoles: ['Soporte academico', 'Hospitality support'],
        requiredSkills: ['Español', 'Atención al cliente'],
        caution: 'La autorizacion para trabajar depende del tipo de visa y permiso.',
      },
      {
        id: 'co-work',
        type: 'sponsored',
        title: 'Visa de trabajo (M)',
        summary: 'Ruta laboral con contrato y patrocinio empresarial.',
        officialUrl: 'https://www.cancilleria.gov.co/tramites_servicios/visa',
        eligibility: ['Oferta laboral formal', 'Cumplimiento de requisitos consulares'],
        typicalRoles: ['Developer', 'Customer support', 'Logistics'],
        requiredSkills: ['React', 'Node.js', 'Logística de almacén'],
        caution: 'Revisar categoria especifica y duracion autorizada.',
      },
    ],
    portals: [
      { id: 'co-computrabajo', name: 'Computrabajo CO', url: 'https://co.computrabajo.com/', category: 'general', sectors: ['all'] },
      { id: 'co-elempleo', name: 'elempleo.com', url: 'https://www.elempleo.com/co/ofertas-empleo/', category: 'general', sectors: ['all'] },
      { id: 'co-servicio', name: 'Servicio Publico de Empleo', url: 'https://www.serviciodeempleo.gov.co/', category: 'government', sectors: ['all'] },
      { id: 'co-linkedin', name: 'LinkedIn Jobs CO', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Brasil': {
    country: 'Brasil',
    visaTracks: [
      {
        id: 'br-student',
        type: 'student',
        title: 'Visto temporario de estudo',
        summary: 'Ruta para estudios en instituciones brasileñas autorizadas.',
        officialUrl: 'https://www.gov.br/mre/pt-br/consulado-londres/visas',
        eligibility: ['Admisión academica', 'Medios economicos', 'Documentacion'],
        typicalRoles: ['Soporte academico', 'Hospitality support'],
        requiredSkills: ['Portugués', 'Atención al cliente'],
        caution: 'Consultar condiciones laborales asociadas a la categoria de visa.',
      },
      {
        id: 'br-work',
        type: 'sponsored',
        title: 'Visto de trabalho temporario',
        summary: 'Ruta laboral con patrocinio empresarial y autorizacion migratoria.',
        officialUrl: 'https://www.gov.br/mj/pt-br/assuntos/seus-direitos/migracoes',
        eligibility: ['Oferta laboral', 'Empresa patrocinadora'],
        typicalRoles: ['Manufactura', 'Logistics', 'IT'],
        requiredSkills: ['Portugués', 'SQL', 'Logística de almacén'],
        caution: 'Revisar lista de documentos y tiempos de autorizacion.',
      },
    ],
    portals: [
      { id: 'br-catho', name: 'Catho', url: 'https://www.catho.com.br/', category: 'general', sectors: ['all'] },
      { id: 'br-infojobs', name: 'InfoJobs Brasil', url: 'https://www.infojobs.com.br/', category: 'general', sectors: ['all'] },
      { id: 'br-sine', name: 'SINE', url: 'https://www.gov.br/trabalho-e-emprego/pt-br', category: 'government', sectors: ['all'] },
      { id: 'br-linkedin', name: 'LinkedIn Jobs BR', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Uruguay': {
    country: 'Uruguay',
    visaTracks: [
      {
        id: 'uy-student',
        type: 'student',
        title: 'Residencia temporal por estudios',
        summary: 'Ruta academica para estudiantes extranjeros con requisitos documentales.',
        officialUrl: 'https://www.gub.uy/tramites/',
        eligibility: ['Admisión academica', 'Documentacion personal', 'Fondos'],
        typicalRoles: ['Soporte academico', 'Hospitality support', 'Retail'],
        requiredSkills: ['Español', 'Atención al cliente'],
        caution: 'Consultar habilitacion laboral segun tipo de residencia.',
      },
      {
        id: 'uy-work',
        type: 'sponsored',
        title: 'Residencia por trabajo',
        summary: 'Ruta de residencia temporal/permanente con vinculo laboral.',
        officialUrl: 'https://www.gub.uy/ministerio-interior/',
        eligibility: ['Oferta laboral', 'Cumplimiento de requisitos migratorios'],
        typicalRoles: ['IT', 'Servicios', 'Logistics support'],
        requiredSkills: ['React', 'SQL', 'Atención al cliente'],
        caution: 'Verificar requisitos de antecedentes y legalizaciones.',
      },
    ],
    portals: [
      { id: 'uy-btj', name: 'BuscoJobs', url: 'https://www.buscojobs.com.uy/', category: 'general', sectors: ['all'] },
      { id: 'uy-computrabajo', name: 'Computrabajo UY', url: 'https://uy.computrabajo.com/', category: 'general', sectors: ['all'] },
      { id: 'uy-via', name: 'ViaTrabajo', url: 'https://viatrabajo.mtss.gub.uy/', category: 'government', sectors: ['all'] },
      { id: 'uy-linkedin', name: 'LinkedIn Jobs UY', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Japón': {
    country: 'Japón',
    visaTracks: [
      {
        id: 'jp-student',
        type: 'student',
        title: 'Student Visa (Japan)',
        summary: 'Ruta academica con trabajo parcial permitido bajo permiso especifico.',
        officialUrl: 'https://www.moj.go.jp/isa/',
        eligibility: ['Admisión educativa', 'COE', 'Fondos y seguro'],
        typicalRoles: ['Language school support', 'Hospitality', 'Part-time retail'],
        requiredSkills: ['Japonés', 'Inglés', 'Atención al cliente'],
        caution: 'Se requiere permiso adicional para actividad fuera del estatus.',
      },
      {
        id: 'jp-skilled',
        type: 'skilled',
        title: 'Engineer/Specialist in Humanities/International Services',
        summary: 'Ruta para roles cualificados en empresa japonesa.',
        officialUrl: 'https://www.moj.go.jp/isa/applications/status/gijinkoku.html',
        eligibility: ['Contrato laboral', 'Perfil cualificado'],
        typicalRoles: ['Developer', 'Data analyst', 'Localization specialist'],
        requiredSkills: ['Java', 'Python', 'SQL', 'Japonés'],
        caution: 'Algunos empleadores exigen nivel JLPT minimo.',
      },
      {
        id: 'jp-wh',
        type: 'work_and_travel',
        title: 'Working Holiday (eligible countries)',
        summary: 'Ruta temporal para viaje y empleo bajo acuerdo bilateral.',
        officialUrl: 'https://www.mofa.go.jp/j_info/visit/w_holiday/index.html',
        eligibility: ['Nacionalidad elegible', 'Edad y fondos minimos'],
        typicalRoles: ['Hospitality', 'Seasonal work', 'Service roles'],
        requiredSkills: ['Japonés', 'Atención al cliente'],
        caution: 'No disponible para todas las nacionalidades.',
      },
    ],
    portals: [
      { id: 'jp-hellowork', name: 'Hello Work', url: 'https://www.hellowork.mhlw.go.jp/', category: 'government', sectors: ['all'] },
      { id: 'jp-indeed', name: 'Indeed Japan', url: 'https://jp.indeed.com/', category: 'general', sectors: ['all'] },
      { id: 'jp-linkedin', name: 'LinkedIn Jobs JP', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'jp-daijob', name: 'Daijob', url: 'https://www.daijob.com/', category: 'niche', sectors: ['multilingual', 'tech'] },
      { id: 'jp-careercross', name: 'CareerCross', url: 'https://www.careercross.com/en', category: 'niche', sectors: ['multilingual', 'tech'] },
    ],
  },
  'Corea del Sur': {
    country: 'Corea del Sur',
    visaTracks: [
      {
        id: 'kr-student',
        type: 'student',
        title: 'D-2 Student Visa',
        summary: 'Ruta academica con reglas de empleo parcial para estudiantes internacionales.',
        officialUrl: 'https://www.immigration.go.kr/',
        eligibility: ['Admisión universitaria', 'Fondos', 'Documentacion migratoria'],
        typicalRoles: ['Campus support', 'Part-time service roles'],
        requiredSkills: ['Coreano', 'Inglés', 'Atención al cliente'],
        caution: 'Consultar permisos de trabajo para estudiantes y limite horario.',
      },
      {
        id: 'kr-work',
        type: 'sponsored',
        title: 'E-series Work Visas',
        summary: 'Ruta laboral para ocupaciones profesionales y tecnicas con sponsor.',
        officialUrl: 'https://www.immigration.go.kr/immigration_eng/1832/subview.do',
        eligibility: ['Contrato laboral', 'Categoria de visa aplicable'],
        typicalRoles: ['Software engineer', 'Manufacturing specialist', 'Language instructor'],
        requiredSkills: ['React', 'TypeScript', 'Coreano', 'Manufactura'],
        caution: 'La categoria exacta de visa depende del puesto y empleador.',
      },
      {
        id: 'kr-wh',
        type: 'work_and_travel',
        title: 'Working Holiday Program',
        summary: 'Ruta temporal para trabajo y viaje de nacionalidades elegibles.',
        officialUrl: 'https://www.whic.kr/',
        eligibility: ['Pais elegible', 'Edad y fondos minimos'],
        typicalRoles: ['Hospitality', 'Service support', 'Seasonal roles'],
        requiredSkills: ['Inglés', 'Coreano', 'Atención al cliente'],
        caution: 'No todas las nacionalidades tienen acuerdo activo.',
      },
    ],
    portals: [
      { id: 'kr-worknet', name: 'WorkNet', url: 'https://www.work.go.kr/', category: 'government', sectors: ['all'] },
      { id: 'kr-jobkorea', name: 'JobKorea', url: 'https://www.jobkorea.co.kr/', category: 'general', sectors: ['all'] },
      { id: 'kr-linkedin', name: 'LinkedIn Jobs KR', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'kr-saramin', name: 'Saramin', url: 'https://www.saramin.co.kr/', category: 'general', sectors: ['all'] },
    ],
  },
  'Singapur': {
    country: 'Singapur',
    visaTracks: [
      {
        id: 'sg-student',
        type: 'student',
        title: 'Student Pass',
        summary: 'Ruta de estudios con trabajo parcial segun elegibilidad institucional.',
        officialUrl: 'https://www.ica.gov.sg/',
        eligibility: ['Oferta educativa aprobada', 'Fondos y requisitos ICA'],
        typicalRoles: ['Campus support', 'Retail', 'Hospitality support'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Verificar politicas de empleo por tipo de institucion y curso.',
      },
      {
        id: 'sg-ep-spass',
        type: 'sponsored',
        title: 'Employment Pass / S Pass',
        summary: 'Ruta laboral patrocinada para perfiles calificados y tecnicos.',
        officialUrl: 'https://www.mom.gov.sg/passes-and-permits',
        eligibility: ['Oferta laboral', 'Salario y perfil segun pass aplicable'],
        typicalRoles: ['Software engineer', 'Data analyst', 'Operations specialist'],
        requiredSkills: ['Python', 'SQL', 'Inglés', 'Logística de almacén'],
        caution: 'Los umbrales salariales y criterios de elegibilidad cambian regularmente.',
      },
    ],
    portals: [
      { id: 'sg-myc', name: 'MyCareersFuture', url: 'https://www.mycareersfuture.gov.sg/', category: 'government', sectors: ['all'] },
      { id: 'sg-jobstreet', name: 'JobStreet SG', url: 'https://www.jobstreet.com.sg/', category: 'general', sectors: ['all'] },
      { id: 'sg-linkedin', name: 'LinkedIn Jobs SG', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'sg-efin', name: 'eFinancialCareers SG', url: 'https://www.efinancialcareers.sg/', category: 'niche', sectors: ['finance', 'tech'] },
    ],
  },
  'China': {
    country: 'China',
    visaTracks: [
      {
        id: 'cn-student',
        type: 'student',
        title: 'X1/X2 Student Visa',
        summary: 'Ruta academica para estudios en instituciones chinas.',
        officialUrl: 'https://www.cs.mfa.gov.cn/wgrlh/lhqz/lhqzjjs/',
        eligibility: ['Admisión', 'Documentos de invitacion', 'Fondos'],
        typicalRoles: ['Internships approved', 'Language exchange support'],
        requiredSkills: ['Mandarín', 'Inglés'],
        caution: 'El trabajo durante estudios requiere autorizacion especifica.',
      },
      {
        id: 'cn-work-z',
        type: 'sponsored',
        title: 'Z Work Visa + Residence Permit',
        summary: 'Ruta laboral para puestos profesionales con sponsor.',
        officialUrl: 'https://english.www.gov.cn/services/workinchina/',
        eligibility: ['Oferta laboral', 'Permiso de trabajo', 'Documentacion sanitaria y legal'],
        typicalRoles: ['Developer', 'Engineer', 'Technical specialist'],
        requiredSkills: ['Mandarín', 'Python', 'Java', 'SQL'],
        caution: 'Requisitos cambian por ciudad y categoria de permiso.',
      },
    ],
    portals: [
      { id: 'cn-zhaopin', name: 'Zhaopin', url: 'https://www.zhaopin.com/', category: 'general', sectors: ['all'] },
      { id: 'cn-51job', name: '51job', url: 'https://www.51job.com/', category: 'general', sectors: ['all'] },
      { id: 'cn-linkedin', name: 'LinkedIn Jobs CN', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'cn-echinacities', name: 'eChinacities', url: 'https://jobs.echinacities.com/', category: 'niche', sectors: ['multilingual', 'education', 'tech'] },
    ],
  },
  'Arabia Saudita': {
    country: 'Arabia Saudita',
    visaTracks: [
      {
        id: 'sa-student',
        type: 'student',
        title: 'Student Visa (Saudi)',
        summary: 'Ruta academica para instituciones autorizadas en Arabia Saudita.',
        officialUrl: 'https://www.moi.gov.sa/',
        eligibility: ['Carta de admision', 'Documentacion consular'],
        typicalRoles: ['Academic support'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Las opciones de empleo para estudiantes son limitadas y reguladas.',
      },
      {
        id: 'sa-work',
        type: 'sponsored',
        title: 'Work Visa (Iqama-sponsored)',
        summary: 'Ruta laboral patrocinada para proyectos de infraestructura y servicios.',
        officialUrl: 'https://www.hrsd.gov.sa/',
        eligibility: ['Oferta laboral', 'Sponsor empresarial', 'Aprobaciones laborales'],
        typicalRoles: ['Construction worker', 'Driver', 'Engineer', 'Logistics support'],
        requiredSkills: ['Albañilería', 'Conducción profesional', 'Logística de almacén', 'Inglés'],
        caution: 'Revisar condiciones contractuales y alojamiento antes de firmar.',
      },
    ],
    portals: [
      { id: 'sa-hrdf', name: 'TAQAT', url: 'https://www.taqat.sa/', category: 'government', sectors: ['all'] },
      { id: 'sa-bayt', name: 'Bayt KSA', url: 'https://www.bayt.com/en/saudi-arabia/jobs/', category: 'general', sectors: ['all'] },
      { id: 'sa-linkedin', name: 'LinkedIn Jobs KSA', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'sa-gulftalent', name: 'GulfTalent KSA', url: 'https://www.gulftalent.com/saudi-arabia/jobs', category: 'niche', sectors: ['construction', 'oil-gas', 'logistics'] },
    ],
  },
  'Emiratos Árabes': {
    country: 'Emiratos Árabes',
    visaTracks: [
      {
        id: 'ae-student',
        type: 'student',
        title: 'UAE Student Visa',
        summary: 'Ruta academica para estudiantes internacionales en EAU.',
        officialUrl: 'https://u.ae/en/information-and-services/visa-and-emirates-id',
        eligibility: ['Admisión educativa', 'Sponsor institucional/familiar'],
        typicalRoles: ['Campus support', 'Service support'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Confirmar condiciones de trabajo permitidas por tipo de visa.',
      },
      {
        id: 'ae-work',
        type: 'sponsored',
        title: 'Employment Visa (UAE)',
        summary: 'Ruta laboral con patrocinio empresarial para sectores de alta rotacion.',
        officialUrl: 'https://u.ae/en/information-and-services/jobs',
        eligibility: ['Contrato laboral', 'Sponsor', 'Aprobaciones medicas'],
        typicalRoles: ['Hospitality', 'Construction', 'Logistics', 'Customer service'],
        requiredSkills: ['Cocina profesional', 'Atención al cliente', 'Logística de almacén', 'Inglés'],
        caution: 'Verifica salario, vivienda y seguro medico en oferta final.',
      },
    ],
    portals: [
      { id: 'ae-mohre', name: 'MOHRE', url: 'https://www.mohre.gov.ae/', category: 'government', sectors: ['all'] },
      { id: 'ae-bayt', name: 'Bayt UAE', url: 'https://www.bayt.com/en/uae/jobs/', category: 'general', sectors: ['all'] },
      { id: 'ae-linkedin', name: 'LinkedIn Jobs UAE', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'ae-gulftalent', name: 'GulfTalent UAE', url: 'https://www.gulftalent.com/uae/jobs', category: 'niche', sectors: ['hospitality', 'construction', 'logistics'] },
      { id: 'ae-catererglobal', name: 'CatererGlobal UAE', url: 'https://www.catererglobal.com/', category: 'niche', sectors: ['hospitality'] },
    ],
  },
  'Qatar': {
    country: 'Qatar',
    visaTracks: [
      {
        id: 'qa-student',
        type: 'student',
        title: 'Qatar Student Visa',
        summary: 'Ruta academica para estudios superiores en Qatar.',
        officialUrl: 'https://www.moi.gov.qa/',
        eligibility: ['Admisión academica', 'Sponsor institucional', 'Documentacion'],
        typicalRoles: ['Campus support roles'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Revisar condiciones laborales para estudiantes.',
      },
      {
        id: 'qa-work',
        type: 'sponsored',
        title: 'Work Residence Permit',
        summary: 'Ruta laboral patrocinada para construccion, salud y servicios.',
        officialUrl: 'https://www.mol.gov.qa/En',
        eligibility: ['Oferta laboral', 'Sponsor empresarial', 'Examenes y permiso'],
        typicalRoles: ['Construction worker', 'Driver', 'Healthcare support', 'Logistics'],
        requiredSkills: ['Albañilería', 'Conducción profesional', 'Logística de almacén', 'Enfermería'],
        caution: 'Verifica condiciones de contrato, descanso y alojamiento.',
      },
    ],
    portals: [
      { id: 'qa-mol', name: 'Ministry of Labour Qatar', url: 'https://www.mol.gov.qa/En', category: 'government', sectors: ['all'] },
      { id: 'qa-bayt', name: 'Bayt Qatar', url: 'https://www.bayt.com/en/qatar/jobs/', category: 'general', sectors: ['all'] },
      { id: 'qa-linkedin', name: 'LinkedIn Jobs Qatar', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'qa-gulftalent', name: 'GulfTalent Qatar', url: 'https://www.gulftalent.com/qatar/jobs', category: 'niche', sectors: ['construction', 'logistics', 'hospitality'] },
    ],
  },
  'Chequia': {
    country: 'Chequia',
    visaTracks: [
      {
        id: 'cz-student',
        type: 'student',
        title: 'Long-term Visa for Study',
        summary: 'Ruta academica para estudios superiores y trabajo parcial regulado.',
        officialUrl: 'https://www.mvcr.cz/mvcren/',
        eligibility: ['Admisión educativa', 'Fondos y alojamiento', 'Seguro medico'],
        typicalRoles: ['Hospitality support', 'Warehouse support', 'Junior office roles'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Revisar reglas de empleo estudiantil vigentes.',
      },
      {
        id: 'cz-employee-card',
        type: 'sponsored',
        title: 'Employee Card',
        summary: 'Ruta laboral con contrato para sectores industriales y tech.',
        officialUrl: 'https://frs.gov.cz/en',
        eligibility: ['Oferta laboral', 'Cumplimiento documental y migratorio'],
        typicalRoles: ['Manufacturing technician', 'Developer', 'Logistics specialist'],
        requiredSkills: ['Manufactura', 'Java', 'Logística de almacén'],
        caution: 'Confirmar requisitos segun ocupacion y empleador.',
      },
    ],
    portals: [
      { id: 'cz-mpsv', name: 'MPSV Job Portal', url: 'https://www.mpsv.cz/web/en', category: 'government', sectors: ['all'] },
      { id: 'cz-jobs', name: 'Jobs.cz', url: 'https://www.jobs.cz/', category: 'general', sectors: ['all'] },
      { id: 'cz-prace', name: 'Prace.cz', url: 'https://www.prace.cz/', category: 'general', sectors: ['all'] },
      { id: 'cz-linkedin', name: 'LinkedIn Jobs CZ', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Finlandia': {
    country: 'Finlandia',
    visaTracks: [
      {
        id: 'fi-student',
        type: 'student',
        title: 'Residence Permit for Studies',
        summary: 'Ruta de estudios con empleo parcial permitido.',
        officialUrl: 'https://migri.fi/en/study-place',
        eligibility: ['Admisión educativa', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Service support', 'Junior IT roles', 'Warehouse support'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Verificar limites de trabajo para estudiantes y renovaciones.',
      },
      {
        id: 'fi-work',
        type: 'sponsored',
        title: 'Residence Permit for Employment',
        summary: 'Ruta laboral para perfiles tech, salud y oficios.',
        officialUrl: 'https://migri.fi/en/work-in-finland',
        eligibility: ['Oferta laboral', 'Condiciones salariales y contractuales'],
        typicalRoles: ['Developer', 'Care worker', 'Engineer'],
        requiredSkills: ['Python', 'React', 'Cuidado de personas mayores'],
        caution: 'Los requisitos varian por tipo de permiso laboral.',
      },
    ],
    portals: [
      { id: 'fi-te', name: 'TE-palvelut', url: 'https://www.te-palvelut.fi/', category: 'government', sectors: ['all'] },
      { id: 'fi-duunitori', name: 'Duunitori', url: 'https://duunitori.fi/', category: 'general', sectors: ['all'] },
      { id: 'fi-oikotie', name: 'Oikotie Jobs', url: 'https://tyopaikat.oikotie.fi/', category: 'general', sectors: ['all'] },
      { id: 'fi-linkedin', name: 'LinkedIn Jobs FI', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Italia': {
    country: 'Italia',
    visaTracks: [
      {
        id: 'it-student',
        type: 'student',
        title: 'Visto studio Italia',
        summary: 'Ruta academica con empleo parcial bajo normativa vigente.',
        officialUrl: 'https://vistoperitalia.esteri.it/home/en',
        eligibility: ['Admisión educativa', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Hospitality support', 'Retail', 'Administrative support'],
        requiredSkills: ['Italiano', 'Inglés', 'Atención al cliente'],
        caution: 'Revisar autorizacion de trabajo para estudiantes extranjeros.',
      },
      {
        id: 'it-work',
        type: 'sponsored',
        title: 'Permesso di soggiorno per lavoro',
        summary: 'Ruta laboral por contrato en sectores demandados.',
        officialUrl: 'https://www.interno.gov.it/it',
        eligibility: ['Oferta laboral', 'Tramite migratorio y cupos de ingreso cuando aplique'],
        typicalRoles: ['Hospitality', 'Agriculture', 'Construction'],
        requiredSkills: ['Cocina profesional', 'Agricultura y campo', 'Albañilería'],
        caution: 'La disponibilidad depende de cupos y decretos anuales.',
      },
    ],
    portals: [
      { id: 'it-cliclavoro', name: 'Cliclavoro', url: 'https://www.cliclavoro.gov.it/', category: 'government', sectors: ['all'] },
      { id: 'it-indeed', name: 'Indeed Italia', url: 'https://it.indeed.com/', category: 'general', sectors: ['all'] },
      { id: 'it-infojobs', name: 'InfoJobs Italia', url: 'https://www.infojobs.it/', category: 'general', sectors: ['all'] },
      { id: 'it-linkedin', name: 'LinkedIn Jobs IT', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Noruega': {
    country: 'Noruega',
    visaTracks: [
      {
        id: 'no-student',
        type: 'student',
        title: 'Residence Permit for Studies',
        summary: 'Ruta academica con trabajo parcial permitido.',
        officialUrl: 'https://www.udi.no/en/want-to-apply/studies/',
        eligibility: ['Admisión educativa', 'Fondos', 'Alojamiento y seguro'],
        typicalRoles: ['Service support', 'Retail assistant', 'Hospitality'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Verificar limite de horas y condiciones de residencia.',
      },
      {
        id: 'no-skilled',
        type: 'skilled',
        title: 'Skilled Worker Permit',
        summary: 'Ruta para perfiles calificados en salud, energia y tecnologia.',
        officialUrl: 'https://www.udi.no/en/want-to-apply/work-immigration/',
        eligibility: ['Oferta laboral', 'Perfil cualificado/documentado'],
        typicalRoles: ['Engineer', 'Nurse', 'Developer', 'Construction specialist'],
        requiredSkills: ['Enfermería', 'Python', 'Albañilería', 'Conducción profesional'],
        caution: 'Revisar requisitos de titulacion o experiencia para cada ocupacion.',
      },
    ],
    portals: [
      { id: 'no-nav', name: 'NAV', url: 'https://www.nav.no/', category: 'government', sectors: ['all'] },
      { id: 'no-finn', name: 'FINN Jobb', url: 'https://www.finn.no/job/fulltime/search.html', category: 'general', sectors: ['all'] },
      { id: 'no-jobbnorge', name: 'Jobbnorge', url: 'https://www.jobbnorge.no/', category: 'general', sectors: ['all'] },
      { id: 'no-linkedin', name: 'LinkedIn Jobs NO', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Polonia': {
    country: 'Polonia',
    visaTracks: [
      {
        id: 'pl-student',
        type: 'student',
        title: 'National Visa D (study)',
        summary: 'Ruta academica para estudios y empleo parcial regulado.',
        officialUrl: 'https://www.gov.pl/web/diplomacy/visas',
        eligibility: ['Admisión educativa', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Warehouse support', 'Service support', 'Junior office'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Confirmar reglas de empleo de estudiantes no-UE.',
      },
      {
        id: 'pl-work',
        type: 'sponsored',
        title: 'Work Permit + Temporary Residence',
        summary: 'Ruta laboral en manufactura, logistica y servicios IT.',
        officialUrl: 'https://www.gov.pl/web/family/work-in-poland',
        eligibility: ['Oferta laboral', 'Permiso de trabajo', 'Residencia temporal'],
        typicalRoles: ['Manufacturing', 'Logistics', 'Developer'],
        requiredSkills: ['Manufactura', 'Logística de almacén', 'Java'],
        caution: 'Los requisitos dependen del voivodato y tipo de permiso.',
      },
    ],
    portals: [
      { id: 'pl-praca', name: 'Praca.gov.pl', url: 'https://www.praca.gov.pl/', category: 'government', sectors: ['all'] },
      { id: 'pl-pracuj', name: 'Pracuj.pl', url: 'https://www.pracuj.pl/', category: 'general', sectors: ['all'] },
      { id: 'pl-justjoin', name: 'Just Join IT', url: 'https://justjoin.it/', category: 'niche', sectors: ['tech'] },
      { id: 'pl-linkedin', name: 'LinkedIn Jobs PL', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Portugal': {
    country: 'Portugal',
    visaTracks: [
      {
        id: 'pt-student',
        type: 'student',
        title: 'Visto de residência para estudo',
        summary: 'Ruta academica con empleo parcial permitido segun marco legal.',
        officialUrl: 'https://imigrante.sef.pt/en/',
        eligibility: ['Admisión educativa', 'Fondos', 'Seguro medico'],
        typicalRoles: ['Hospitality', 'Retail', 'Service support'],
        requiredSkills: ['Portugués', 'Inglés', 'Atención al cliente'],
        caution: 'Consultar condiciones de empleo para estudiantes y renovacion.',
      },
      {
        id: 'pt-work',
        type: 'sponsored',
        title: 'Visa para trabalho subordinado',
        summary: 'Ruta laboral por contrato para sectores con demanda.',
        officialUrl: 'https://vistos.mne.gov.pt/en/national-visas/general-information/type-of-visas',
        eligibility: ['Oferta laboral', 'Contrato y tramite migratorio'],
        typicalRoles: ['Hospitality', 'Logistics', 'Tech support'],
        requiredSkills: ['Cocina profesional', 'Logística de almacén', 'React'],
        caution: 'Revisar requisitos de contrato y validacion documental.',
      },
    ],
    portals: [
      { id: 'pt-iefp', name: 'IEFP NetEmprego', url: 'https://iefponline.iefp.pt/', category: 'government', sectors: ['all'] },
      { id: 'pt-netempregos', name: 'Net-Empregos', url: 'https://www.net-empregos.com/', category: 'general', sectors: ['all'] },
      { id: 'pt-itjobs', name: 'ITJobs', url: 'https://pt.itjobs.pt/', category: 'niche', sectors: ['tech'] },
      { id: 'pt-linkedin', name: 'LinkedIn Jobs PT', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Argentina': {
    country: 'Argentina',
    visaTracks: [
      {
        id: 'ar-student',
        type: 'student',
        title: 'Residencia temporaria por estudios',
        summary: 'Ruta academica para estudiantes internacionales con requisitos migratorios.',
        officialUrl: 'https://www.argentina.gob.ar/interior/migraciones',
        eligibility: ['Admisión educativa', 'Documentacion', 'Medios economicos'],
        typicalRoles: ['Support roles', 'Retail support'],
        requiredSkills: ['Español', 'Atención al cliente'],
        caution: 'Verificar habilitacion de empleo segun categoria migratoria.',
      },
      {
        id: 'ar-work',
        type: 'sponsored',
        title: 'Residencia temporaria por trabajo',
        summary: 'Ruta laboral con contrato y patrocinio empleador cuando aplique.',
        officialUrl: 'https://www.argentina.gob.ar/trabajo',
        eligibility: ['Oferta laboral', 'Documentacion legalizada'],
        typicalRoles: ['IT services', 'Logistics', 'Customer support'],
        requiredSkills: ['React', 'SQL', 'Atención al cliente'],
        caution: 'Revisar requisitos vigentes para nacionalidades no-Mercosur.',
      },
    ],
    portals: [
      { id: 'ar-bne', name: 'Portal Empleo (BNE)', url: 'https://www.portalempleo.gob.ar/', category: 'government', sectors: ['all'] },
      { id: 'ar-bumeran', name: 'Bumeran', url: 'https://www.bumeran.com.ar/', category: 'general', sectors: ['all'] },
      { id: 'ar-zonajobs', name: 'ZonaJobs', url: 'https://www.zonajobs.com.ar/', category: 'general', sectors: ['all'] },
      { id: 'ar-linkedin', name: 'LinkedIn Jobs AR', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
  'Rusia': {
    country: 'Rusia',
    visaTracks: [
      {
        id: 'ru-student',
        type: 'student',
        title: 'Student Visa (Russia)',
        summary: 'Ruta academica para estudios en instituciones rusas acreditadas.',
        officialUrl: 'https://evisa.kdmid.ru/',
        eligibility: ['Admisión educativa', 'Documentación consular', 'Fondos'],
        typicalRoles: ['Soporte academico', 'Roles de apoyo institucional'],
        requiredSkills: ['Ruso', 'Inglés'],
        caution: 'Verificar reglas locales de empleo para estudiantes extranjeros.',
      },
      {
        id: 'ru-work',
        type: 'sponsored',
        title: 'Work Visa (employer-sponsored)',
        summary: 'Ruta laboral con invitación y patrocinio de empleador.',
        officialUrl: 'https://www.gosuslugi.ru/',
        eligibility: ['Oferta laboral', 'Invitacion de empleador', 'Permisos migratorios'],
        typicalRoles: ['Engineer', 'Developer', 'Technical specialist'],
        requiredSkills: ['Ruso', 'Python', 'C++', 'SQL'],
        caution: 'Revisar elegibilidad legal y condiciones contractuales antes de postular.',
      },
    ],
    portals: [
      { id: 'ru-hh', name: 'HeadHunter', url: 'https://hh.ru/', category: 'general', sectors: ['all'] },
      { id: 'ru-superjob', name: 'SuperJob', url: 'https://www.superjob.ru/', category: 'general', sectors: ['all'] },
      { id: 'ru-linkedin', name: 'LinkedIn Jobs RU', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
      { id: 'ru-gos', name: 'Gosuslugi', url: 'https://www.gosuslugi.ru/', category: 'government', sectors: ['all'] },
    ],
  },
  'Sudáfrica': {
    country: 'Sudáfrica',
    visaTracks: [
      {
        id: 'za-student',
        type: 'student',
        title: 'Study Visa (South Africa)',
        summary: 'Ruta academica para estudios formales en Sudafrica.',
        officialUrl: 'http://www.dha.gov.za/',
        eligibility: ['Admisión', 'Fondos', 'Seguro y requisitos consulares'],
        typicalRoles: ['Academic support', 'Retail support'],
        requiredSkills: ['Inglés', 'Atención al cliente'],
        caution: 'Confirmar condiciones de empleo para estudiantes extranjeros.',
      },
      {
        id: 'za-critical',
        type: 'skilled',
        title: 'Critical Skills Work Visa',
        summary: 'Ruta para ocupaciones en lista critica con alta demanda local.',
        officialUrl: 'http://www.dha.gov.za/index.php/immigration-services/types-of-visas',
        eligibility: ['Perfil en ocupacion critica', 'Documentacion profesional'],
        typicalRoles: ['Software developer', 'Engineer', 'Data professional'],
        requiredSkills: ['Python', 'React', 'SQL', 'Inglés'],
        caution: 'Revisar lista de critical skills actualizada y requisitos de registro profesional.',
      },
    ],
    portals: [
      { id: 'za-ess', name: 'Employment Services of South Africa', url: 'https://essa.labour.gov.za/EssaOnline/WebBeans/', category: 'government', sectors: ['all'] },
      { id: 'za-careerjunction', name: 'CareerJunction', url: 'https://www.careerjunction.co.za/', category: 'general', sectors: ['all'] },
      { id: 'za-pnet', name: 'PNet', url: 'https://www.pnet.co.za/', category: 'general', sectors: ['all'] },
      { id: 'za-linkedin', name: 'LinkedIn Jobs ZA', url: 'https://www.linkedin.com/jobs/', category: 'general', sectors: ['all'] },
    ],
  },
};
